spring:
  cloud:
    function:
      definition: hello
    stream:
      bindings:
        hello-in-0:
          group: kafka-stream-client
          destination: hello.out
          binder: kafka
      kafka:
        binder:
          brokers: localhost
          defaultBrokerPort: 29092
          enable-observation: true
  application:
    name: kafka-stream-client
  data:
    mongodb:
      database: stream

management:
  metrics:
    mongo:
      command:
        enabled: false
  tracing:
    sampling:
      probability: 1.0
    enabled: true
    propagation:
      type: w3c
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
server:
  port: 8083

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
