spring:
  reactor:
    context-propagation: auto
  cloud:
    function:
      definition: helloReactive
    stream:
      bindings:
        helloReactive-in-0:
          group: kafka-stream-reactive-proxy
          destination: hello.in
          binder: kafka
        helloReactive-out-0:
          group: kafka-stream-reactive-proxy
          destination: hello.out
          binder: kafka
      kafka:
        binder:
          brokers: localhost
          defaultBrokerPort: 29092
          enable-observation: true
  application:
    name: kafka-stream-reactive-proxy

management:
  tracing:
    sampling:
      probability: 1.0
    enabled: true
    propagation:
      type: w3c
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
server:
  port: 8084

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
